### ISSUE TITLE
Deprecation Warning : Using / for division outside of calc

### ISSUE THREAD

**Issue by leosin** [Snippetors/snippetors.github.io#1]
i'm using vuepress-plugin-tabs on vuepress next

how do i fix it?
![image](https://user-images.githubusercontent.com/3676670/158115747-45411d3d-25d9-4cf8-94b5-c23954e30ed5.png)

**Comment by LucienZhang** [comment]
use version 1.1.7

**Comment by leosin** [comment]
thanks 🙏👍
